pip install pyttsx3
pip install webbrowser
pip install smtplib
pip install random
pip install speech_recognition
pip install wikipedia
pip install datetime
pip install wolframalpha
pip install  sounddevice
pip scipy.io.wavfile pip install  write
pip install PyQt5
pip install  sys
pip install playsound
pip install  datetime 
pip install gpiozero
pip install tkinter
pip install tkinter
pip install pygame
pip install cv